### ISSUE TITLE
Multiple data source

### ISSUE THREAD

**Issue by rybarova** [petitphp/facetwp-monthly#4]
Hello, your plugin works well with 1 data source, but I need to use that with 2 data source.

I have CPT 'Events' with ACF 'DateFrom' and 'DateTo' and at this time i can use only 1 of these. That is problem if event start 30 jun. and end 10 jul. A similiar workings is in facet type 'Date Rage'. Is here any way how to do same with Your plguin? Can you add that option or I must edit source of your plugin by myself?

Thank you for your time.

**Comment by petitphp** [comment]
Hey @rybarova

It's been a while since I use FacetWP, but I think what you want achieve is doable. Since the "Date Range" facet type support multiple data source you could start from here and create a new facet type from it. You can change the way your new facet type filter results using what facet monthly does as a base (you would need to modify the query to use the two data-source instead of one).

Hope this helps.
